EDUCATION_PATTERNS = [
    r'\b(?:elementary\s?school|elementary\s?education)\b',
    r'\b(?:high\s?school|secondary\s?school|sma)\b',
    r'\b(?:senior\s?high\s?school|shs)\b',
    r'\b(?:college|university|undergraduate|diploma|vocational\s?school|trade\s?school)\b',
    r'\b(?:associate(?:\'s)? degree|a\.?s\.?|associate(?:\'s)? of\s?science)\b',
    r'\b(?:bachelor(?:\'s)? of science|bachelor(?:\'s)? degree|b\.?s\.?|b\.?e(?:\.)?|bs)\b',
    r'\b(?:bachelor(?:\'s)? of arts|b\.?a(?:\.)?|ba)\b',
    r'\b(?:bachelor(?:\'s)? of commerce|b\.?com(?:\.)?|bcom)\b',
    r'\b(?:bachelor(?:\'s)? of technology|b\.?tech(?:nology)?|btech)\b',
    r'\b(?:bachelor(?:\'s)? of engineering|b\.?eng(?:\.)?|beng)\b',
    r'\b(?:master(?:\'s)? of science|master(?:\'s)? degree|m\.?s\.?|m\.?e(?:\.)?|ms)\b',
    r'\b(?:master(?:\'s)? of arts|m\.?a(?:\.)?|ma)\b',
    r'\b(?:master(?:\'s)? of commerce|m\.?com(?:\.)?|mcom)\b',
    r'\b(?:master(?:\'s)? of technology|m\.?tech(?:nology)?|mtech)\b',
    r'\b(?:master(?:\'s)? of engineering|m\.?eng(?:\.)?|meng)\b',
    r'\b(?:doctor(?:ate)? of philosophy|ph\.?d\.?|dph)\b',
    r'\b(?:doctor(?:ate)? of\s?education|ed\.?d\.?|edd)\b',
    r'\b(?:bachelor(?:\'s)? of fine arts|b\.?f\.?a\.?|bfa)\b',
    r'\b(?:master(?:\'s)? of fine arts|m\.?f\.?a\.?|mfa)\b',
    r'\b(?:bachelor(?:\'s)? of business\s?administration|b\.?b\.?a\.?|bba)\b',
    r'\b(?:master(?:\'s)? of business\s?administration|m\.?b\.?a\.?|mba)\b',
    r'\b(?:certificate|certification|credential)\b',

    # Additional Patterns
    r'\b(?:diploma in engineering|engineering diploma)\b',
    r'\b(?:diploma in computer science|computer science diploma)\b',
    r'\b(?:diploma in graphic design|graphic design diploma)\b',
    r'\b(?:diploma in nursing|nursing diploma)\b',
    r'\b(?:associate of applied science|a\.?a\.?s\.?|aas)\b',
    r'\b(?:associate of arts|a\.?a\.?|aa)\b',
    r'\b(?:bachelor of science in engineering|b\.?s\.?e(?:\.)?|bse)\b',
    r'\b(?:bachelor of science in graphic design|b\.?s\.?g(?:\.)?|bsg)\b',
    r'\b(?:bachelor of science in management of human resources|b\.?s\.?mhr(?:\.)?)\b',
    r'\b(?:ba in film and television|b\.?s\.?ft(?:\.)?)\b', 
    r'\b(?:bachelor of science in nursing|b\.?s\.?n(?:\.)?|bsn)\b',
    r'\b(?:bachelor of science in human|b\.?s\.?h(?:\.)?)\b',
    r'\b(?:bachelor of fine arts in dance|b\.?f\.?a\.?d(?:\.)?|bfad)\b',
    r'\b(?:bachelor of science in education|b\.?s\.?ed(?:\.)?|bse)\b',
    r'\b(?:bachelor of social work|b\.?s\.?w(?:\.)?|bsw)\b',
    r'\b(?:bachelor of business administration|b\.?b\.?a\.?|bba)\b',
    r'\b(?:bachelor of science in management|b\.?b\.?a\.?|bsm)\b',
    r'\b(?:master of public administration|m\.?p\.?a(?:\.)?|mpa)\b',
    r'\b(?:master of public health|m\.?p\.?h(?:\.)?|mph)\b',
    r'\b(?:master of social work|m\.?s\.?w(?:\.)?|msw)\b',
    r'\b(?:doctor of education|ed\.?d\.?|edd)\b',
    r'\b(?:doctor of nursing practice|d\.?n\.?p(?:\.)?|dnp)\b',
    r'\b(?:associate of business administration|a\.?b\.?a\.?|aba)\b',
    r'\b(?:bachelor of science in information technology|b\.?s\.?it(?:\.)?|bsit)\b',
    #For increasing efficiency in BSIT courses:
    r'\b(?:information technology|b\.?s\.?it(?:\.)?|bsit)\b',
    r'\b(?:bachelor of science in computer engineering|b\.?s\.?c\.?e(?:\.)?|bsce)\b',
    r'\b(?:bachelor of arts in psychology|b\.?a\.?p(?:\.)?|bap)\b',
    r'\b(?:bachelor of arts in history|b\.?a\.?h(?:\.)?|bah)\b',
    r'\b(?:bachelor of science in business administration|b\.?s\.?ba(?:\.)?|bsba)\b',
    r'\b(?:bachelor of arts in sociology|b\.?a\.?s(?:\.)?|bas)\b',
    r'\b(?:bachelor of science in biology|b\.?s\.?b(?:\.)?|bsb)\b',
    r'\b(?:master of science in computer science|m\.?s\.?cs(?:\.)?|mscs)\b',
    r'\b(?:master of science in cybersecurity|m\.?s\.?cyber(?:\.)?|mscyber)\b',
    r'\b(?:master of science in data science|m\.?s\.?ds(?:\.)?|msds)\b',
    r'\b(?:doctor of business administration|d\.?b\.?a(?:\.)?|dba)\b',
    r'\b(?:doctor of psychology|p\.?s\.?y\.?d(?:\.)?|psy.d)\b',
    r'\b(?:associate of liberal arts|a\.?l\.?a(?:\.)?|ala)\b',
    r'\b(?:bachelor of music|b\.?m\.?u(?:\.)?|bmu)\b',
    r'\b(?:bachelor of arts in communication|b\.?a\.?c(?:\.)?|bac)\b',
    r'\b(?:master of arts in communication|m\.?a\.?c(?:\.)?|mac)\b',
    r'\b(?:diploma in hospitality management|hospitality management diploma)\b',
    r'\b(?:bachelor of science in hospitality management|b\.?s\.?hm(?:\.)?|bshm)\b',
    r'\b(?:bachelor of science in environmental science|b\.?s\.?es(?:\.)?|bses)\b',
    r'\b(?:bachelor of science in physics|b\.?s\.?phy(?:\.)?|bsphy)\b',
    r'\b(?:bachelor of arts in philosophy|b\.?a\.?ph(?:\.)?|baph)\b',
    r'\b(?:bachelor of arts in literature|b\.?a\.?lit(?:\.)?|balit)\b',
    r'\b(?:bachelor of engineering in civil engineering|b\.?e\.?c\.?e(?:\.)?|bec)\b',
    r'\b(?:master of engineering in civil engineering|m\.?e\.?c\.?e(?:\.)?|mec)\b',
    r'\b(?:bachelor of science in mathematics|b\.?s\.?math(?:\.)?|bsmath)\b',
    r'\b(?:bachelor of science in statistics|b\.?s\.?stat(?:\.)?|bsstat)\b',
    r'\b(?:bachelor of arts in anthropology|b\.?a\.?an(?:\.)?|baan)\b',
    r'\b(?:bachelor of arts in geography|b\.?a\.?geog(?:\.)?|baGeog)\b',
    r'\b(?:bachelor of arts in foreign languages|b\.?a\.?fl(?:\.)?|baFL)\b',
    r'\b(?:bachelor of arts in marketing|b\.?a\.?mkt(?:\.)?|baMkt)\b',
    r'\b(?:master of science in finance|m\.?s\.?fin(?:\.)?|msfin)\b',
    r'\b(?:master of science in accounting|m\.?s\.?acct(?:\.)?|msacct)\b',
    r'\b(?:bachelor of arts in graphic design|b\.?a\.?gd(?:\.)?|baGD)\b',
    r'\b(?:bachelor of fine arts in photography|b\.?f\.?a\.?p(?:\.)?|bfaP)\b',
    
    r'\b(?:elementary\s?school|elementary\s?education)\b',
    r'\b(?:high\s?school|secondary\s?school|sma)\b',
    r'\b(?:senior\s?high\s?school|shs)\b',
    r'\b(?:college|university|undergraduate|diploma|vocational\s?school|trade\s?school)\b',
    r'\b(?:associate(?:\'s)? degree|a\.?s\.?|associate(?:\'s)? of\s?science)\b',
    r'\b(?:bachelor(?:\'s)? of science|bachelor(?:\'s)? degree|b\.?s\.?|b\.?e(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of arts|b\.?a(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of commerce|b\.?com(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of technology|b\.?tech(?:nology)?)\b',
    r'\b(?:bachelor(?:\'s)? of engineering|b\.?eng(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of science|master(?:\'s)? degree|m\.?s\.?|m\.?e(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of arts|m\.?a(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of commerce|m\.?com(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of technology|m\.?tech(?:nology)?)\b',
    r'\b(?:master(?:\'s)? of engineering|m\.?eng(?:\.)?)\b',
    r'\b(?:doctor(?:ate)? of philosophy|ph\.?d\.?)\b',
    r'\b(?:doctor(?:ate)? of\s?education|ed\.?d\.?)\b',
    r'\b(?:bachelor(?:\'s)? of fine arts|b\.?f\.?a\.?)\b',
    r'\b(?:master(?:\'s)? of fine arts|m\.?f\.?a\.?)\b',
    r'\b(?:bachelor(?:\'s)? of business\s?administration|b\.?b\.?a\.?)\b',
    r'\b(?:master(?:\'s)? of business\s?administration|m\.?b\.?a\.?)\b',
    r'\b(?:certificate|certification|credential)\b',
    
    # Additional Patterns
    r'\b(?:diploma in engineering|engineering diploma)\b',
    r'\b(?:diploma in computer science|computer science diploma)\b',
    r'\b(?:diploma in graphic design|graphic design diploma)\b',
    r'\b(?:diploma in nursing|nursing diploma)\b',
    r'\b(?:associate of applied science|a\.?a\.?s\.?)\b',
    r'\b(?:associate of arts|a\.?a\.?)\b',
    r'\b(?:bachelor of science in engineering|b\.?s\.?e(?:\.)?)\b',
    r'\b(?:bachelor of science in graphic design|b\.?s\.?e(?:\.)?)\b',
    r'\b(?:bachelor of science in management of human resources|b\.?s\.?e(?:\.)?)\b',
    r'\b(?:bachelor of science in nursing|b\.?s\.?n(?:\.)?)\b',
    r'\b(?:bachelor of science in human|b\.?s\.?n(?:\.)?)\b',
    r'\b(?:bachelor of fine arts in dance|b\.?f\.?a\.?d(?:\.)?)\b',
    r'\b(?:bachelor of science in education|b\.?s\.?ed(?:\.)?)\b',
    r'\b(?:bachelor of social work|b\.?s\.?w(?:\.)?)\b',
    r'\b(?:bachelor of arts in film and television|b\.?s\.?w(?:\.)?)\b',
    r'\b(?:bachelor of of business administration|b\.?s\.?w(?:\.)?)\b',
    r'\b(?:master of public administration|m\.?p\.?a(?:\.)?)\b',
    r'\b(?:master of public health|m\.?p\.?h(?:\.)?)\b',
    r'\b(?:master of social work|m\.?s\.?w(?:\.)?)\b',
    r'\b(?:doctor of education|ed\.?d\.?)\b',
    r'\b(?:doctor of nursing practice|d\.?n\.?p(?:\.)?)\b',
    r'\b(?:associate of business administration|a\.?b\.?a\.?)\b',
    r'\b(?:bachelor of science in information technology|b\.?s\.?it(?:\.)?)\b',
    r'\b(?:bachelor of science in computer engineering|b\.?s\.?c\.?e(?:\.)?)\b',
    r'\b(?:bachelor of arts in psychology|b\.?a\.?p(?:\.)?)\b',
    r'\b(?:bachelor of arts in history|b\.?a\.?h(?:\.)?)\b',
    r'\b(?:bachelor of science in business administration|b\.?a\.?h(?:\.)?)\b',
    r'\b(?:bachelor of arts in sociology|b\.?a\.?s(?:\.)?)\b',
    r'\b(?:bachelor of science in biology|b\.?s\.?b(?:\.)?)\b',
    r'\b(?:master of science in computer science|m\.?s\.?cs(?:\.)?)\b',
    r'\b(?:master of science in cybersecurity|m\.?s\.?cyber(?:\.)?)\b',
    r'\b(?:master of science in data science|m\.?s\.?ds(?:\.)?)\b',
    r'\b(?:doctor of business administration|d\.?b\.?a(?:\.)?)\b',
    r'\b(?:doctor of psychology|p\.?s\.?y\.?d(?:\.)?)\b',
    r'\b(?:associate of liberal arts|a\.?l\.?a(?:\.)?)\b',
    r'\b(?:bachelor of music|b\.?m\.?u(?:\.)?)\b',
    r'\b(?:bachelor of arts in communication|b\.?a\.?c(?:\.)?)\b',
    r'\b(?:master of arts in communication|m\.?a\.?c(?:\.)?)\b',
    r'\b(?:diploma in hospitality management|hospitality management diploma)\b',
    r'\b(?:bachelor of science in hospitality management|b\.?s\.?hm(?:\.)?)\b',
    r'\b(?:bachelor of science in environmental science|b\.?s\.?es(?:\.)?)\b',
    r'\b(?:bachelor of science in physics|b\.?s\.?phy(?:\.)?)\b',
    r'\b(?:bachelor of arts in philosophy|b\.?a\.?ph(?:\.)?)\b',
    r'\b(?:bachelor of arts in literature|b\.?a\.?lit(?:\.)?)\b',
    r'\b(?:bachelor of engineering in civil engineering|b\.?e\.?c\.?e(?:\.)?)\b',
    r'\b(?:master of engineering in civil engineering|m\.?e\.?c\.?e(?:\.)?)\b',
    r'\b(?:bachelor of science in mathematics|b\.?s\.?math(?:\.)?)\b',
    r'\b(?:bachelor of science in statistics|b\.?s\.?stat(?:\.)?)\b',
    r'\b(?:bachelor of arts in anthropology|b\.?a\.?an(?:\.)?)\b',
    r'\b(?:bachelor of arts in geography|b\.?a\.?geog(?:\.)?)\b',
    r'\b(?:bachelor of arts in foreign languages|b\.?a\.?fl(?:\.)?)\b',
    r'\b(?:bachelor of arts in marketing|b\.?a\.?mkt(?:\.)?)\b',
    r'\b(?:master of science in finance|m\.?s\.?fin(?:\.)?)\b',
    r'\b(?:master of science in accounting|m\.?s\.?acct(?:\.)?)\b',
    r'\b(?:bachelor of arts in graphic design|b\.?a\.?gd(?:\.)?)\b',
    r'\b(?:master of fine arts in creative writing|m\.?f\.?a\.?cw(?:\.)?)\b',
    r'\b(?:associate of fine arts|a\.?f\.?a(?:\.)?)\b',
    r'\b(?:certificate in project management|project management certificate)\b',
    r'\b(?:bachelor of arts in film|b\.?a\.?film(?:\.)?)\b',
    r'\b(?:master of science in information systems|m\.?s\.?is(?:\.)?)\b',
    r'\b(?:master of science in business analytics|m\.?s\.?ba(?:\.)?)\b',
    r'\b(?:bachelor of science in health sciences|b\.?s\.?hs(?:\.)?)\b',
    r'\b(?:master of science in health administration|m\.?s\.?ha(?:\.)?)\b',
    r'\b(?:diploma in digital marketing|digital marketing diploma)\b',
    r'\b(?:bachelor of arts in digital media|b\.?a\.?dm(?:\.)?)\b',
    r'\b(?:master of science in cybersecurity policy|m\.?s\.?cyberpol(?:\.)?)\b',
    r'\b(?:associate of health sciences|a\.?h\.?s(?:\.)?)\b',
    r'\b(?:bachelor of health administration|b\.?h\.?a(?:\.)?)\b',
    r'\b(?:diploma in web development|web development diploma)\b',
    r'\b(?:certificate in digital photography|digital photography certificate)\b',
    r'\b(?:bachelor of arts in visual arts|b\.?a\.?va(?:\.)?)\b',
    r'\b(?:bachelor of science in neuroscience|b\.?s\.?neuro(?:\.)?)\b',
    r'\b(?:bachelor of arts in ethics|b\.?a\.?eth(?:\.)?)\b',
    r'\b(?:master of arts in sociology|m\.?a\.?soc(?:\.)?)\b',
    r'\b(?:diploma in interior design|interior design diploma)\b',
    r'\b(?:associate of applied technology|a\.?a\.?t(?:\.)?)\b',
    r'\b(?:master of arts in international relations|m\.?a\.?ir(?:\.)?)\b',
    r'\b(?:bachelor of arts in gender studies|b\.?a\.?gs(?:\.)?)\b',
    r'\b(?:bachelor of fine arts in photography|b\.?f\.?a\.?p(?:\.)?)\b',
    r'\b(?:master of arts in public policy|m\.?a\.?pp(?:\.)?)\b',
    r'\b(?:diploma in landscape architecture|landscape architecture diploma)\b',
    r'\b(?:bachelor of arts in dance|b\.?a\.?dance(?:\.)?)\b',
    r'\b(?:bachelor of science in aerospace engineering|b\.?s\.?ae(?:\.)?)\b',
    r'\b(?:master of engineering in aerospace engineering|m\.?e\.?ae(?:\.)?)\b',

    r'\b(?:bachelor(?:\'s)? of health sciences|b\.?h\.?s(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of biomedical sciences|b\.?b\.?s(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of exercise science|b\.?e\.?s(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of social sciences|b\.?s\.?s(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of agricultural sciences|b\.?a\.?s(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of environmental studies|b\.?e\.?s(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of urban studies|b\.?u\.?s(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of hospitality and tourism|b\.?h\.?t(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of health administration|m\.?h\.?a(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of information systems|m\.?i\.?s(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of supply chain management|m\.?s\.?c\.?m(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of data analytics|m\.?d\.?a(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of education leadership|m\.?e\.?l(?:\.)?)\b',
    r'\b(?:doctor(?:ate)? of nursing practice|d\.?n\.?p(?:\.)?)\b',
    r'\b(?:doctor(?:ate)? of management|d\.?m(?:\.)?)\b',
    r'\b(?:doctor(?:ate)? of social work|d\.?s\.?w(?:\.)?)\b',
    r'\b(?:doctor(?:ate)? of engineering|d\.?e(?:\.)?)\b',
    r'\b(?:associate of science in nursing|a\.?s\.?n(?:\.)?)\b',
    r'\b(?:associate of applied arts|a\.?a\.?a(?:\.)?)\b',
    r'\b(?:associate of science in computer science|a\.?s\.?cs(?:\.)?)\b',
    r'\b(?:associate of technology|a\.?t(?:\.)?)\b',
    r'\b(?:diploma in information technology|it diploma)\b',
    r'\b(?:diploma in graphic arts|graphic arts diploma)\b',
    r'\b(?:diploma in business administration|business administration diploma)\b',
    r'\b(?:certificate in project management|project management certificate)\b',
    r'\b(?:certificate in digital marketing|digital marketing certificate)\b',
    r'\b(?:certificate in web development|web development certificate)\b',
    r'\b(?:certificate in data analysis|data analysis certificate)\b',
    r'\b(?:bachelor(?:\'s)? of fine arts in graphic design|b\.?f\.?a\.?g\.?d(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of fine arts in visual arts|b\.?f\.?a\.?v\.?a(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of arts in visual communication|m\.?a\.?v\.?c(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of design|m\.?d(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of architecture|m\.?arch(?:\.)?)\b',
    r'\b(?:doctor(?:ate)? of architecture|d\.?arch(?:\.)?)\b',
    r'\b(?:doctor(?:ate)? of design|d\.?d(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of environmental engineering|b\.?e\.?e(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of marine biology|b\.?m\.?b(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of applied physics|b\.?a\.?p(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of molecular biology|b\.?m\.?b(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of public health|b\.?p\.?h(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of clinical psychology|b\.?c\.?p(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of clinical psychology|m\.?c\.?p(?:\.)?)\b',
    r'\b(?:doctor(?:ate)? of clinical psychology|d\.?c\.?p(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of criminology|b\.?c\.?r(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of forensic science|b\.?f\.?s(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of forensic science|m\.?f\.?s(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of education in special education|b\.?e\.?s\.?e(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of education in early childhood|b\.?e\.?e\.?c(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of education in counseling|m\.?e\.?c(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of education in curriculum and instruction|m\.?e\.?ci(?:\.)?)\b',
    r'\b(?:certificate in teaching English as a second language|tesol certificate)\b',
    r'\b(?:certificate in adult education|adult education certificate)\b',
    r'\b(?:bachelor(?:\'s)? of science in accounting|b\.?s\.?acc(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of science in accounting|m\.?s\.?acc(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of finance|b\.?fin(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of economics|b\.?eco(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of economics|m\.?eco(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of marketing|b\.?mkt(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of marketing|m\.?mkt(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of international relations|b\.?i\.?r(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of international relations|m\.?i\.?r(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of political science|b\.?p\.?s(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of political science|m\.?p\.?s(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of sociology|b\.?s\.?o(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of sociology|m\.?s\.?o(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of anthropology|b\.?a\.?n(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of anthropology|m\.?a\.?n(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of history|b\.?h\.?i(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of history|m\.?h\.?i(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of philosophy|b\.?p\.?h(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of philosophy|m\.?p\.?h(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of fine arts in theatre|b\.?f\.?a\.?t(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of fine arts in theatre|m\.?f\.?a\.?t(?:\.)?)\b',
    r'\b(?:bachelor(?:\'s)? of fine arts in music|b\.?f\.?a\.?m(?:\.)?)\b',
    r'\b(?:master(?:\'s)? of fine arts in music|m\.?f\.?a\.?m(?:\.)?)\b',

    
]
