SKILLS_DB = [
    'machine learning', 'data science', 'python', 'word', 'excel', 'english', 'java', 'javascript', 'sql',
    'tableau', 'power bi', 'project management', 'leadership', 'communication skills', 'problem-solving',
    'html', 'css', 'git', 'github', 'gitlab', 'agile methodologies', 'scrum', 'kanban', 'customer service',
    'mysql', 'postgresql', 'oracle', 'db2', 'sql server', 'mongodb', 'cassandra', 'couchbase', 'redis', 'firebase',
    'graphql', 'rest', 'json', 'xml', 'django', 'flask', 'node.js', 'react', 'angular', 'vue.js', 'typescript',
    'bootstrap', 'tailwind css', 'webpack', 'docker', 'kubernetes', 'jenkins', 'ci/cd', 'aws', 'azure', 'gcp', 
    'terraform', 'ansible', 'linux', 'bash scripting', 'powershell', 'application programming', 'system administration',
    'networking', 'cybersecurity', 'penetration testing', 'ethical hacking', 'cloud computing', 'big data', 'hadoop',
    'spark', 'tensorflow', 'keras', 'pytorch', 'nlp', 'computer vision', 'devops', 'iot', 'robotics', 'automation',
    'sas', 'matlab', 'statistics', 'data visualization', 'business intelligence', 'salesforce', 'crm', 'erp', 'sap',
    'enterprise architecture', 'virtualization', 'vmware', 'hyper-v', 'financial modeling', 'financial analysis',
    'budgeting', 'forecasting', 'risk management', 'supply chain management', 'logistics', 'procurement',
    'vendor management', 'negotiation', 'business strategy', 'market research', 'product management', 'pricing strategy',
    'customer relationship management', 'seo', 'digital marketing', 'social media marketing', 'email marketing',
    'content creation', 'copywriting', 'advertising', 'google analytics', 'facebook ads', 'google ads', 'ppc', 'sem',
    'branding', 'product development', 'ux design', 'ui design', 'graphic design', 'adobe photoshop', 'adobe illustrator',
    'adobe xd', 'figma', 'sketch', 'prototyping', 'wireframing', 'video editing', 'final cut pro', 'adobe premiere',
    'motion graphics', 'after effects', 'animation', '3d modeling', 'autocad', 'solidworks', 'blender', 'maya',
    '3ds max', 'cinema 4d', 'game development', 'unity', 'unreal engine', 'game design', 'qa testing', 'unit testing',
    'automation testing', 'selenium', 'junit', 'jest', 'mocha', 'cypress', 'performance testing', 'penetration testing',
    'risk assessment', 'threat analysis', 'incident response', 'information security', 'vulnerability management',
    'network security', 'firewall configuration', 'identity and access management', 'penetration testing tools',
    'metasploit', 'burp suite', 'wireshark', 'nmap', 'ethical hacking', 'red teaming', 'blue teaming', 'incident response',
    'forensic analysis', 'disaster recovery', 'business continuity', 'regulatory compliance', 'gdpr', 'hipaa', 'pci dss',
    'iso 27001', 'soc 2', 'enterprise risk management', 'quantitative analysis', 'data wrangling', 'etl', 'data mining',
    'bigquery', 'apache airflow', 'apache kafka', 'data lake', 'data warehouse', 'data governance', 'data quality',
    'etl pipelines', 'snowflake', 'informatica', 'talend', 'data modeling', 'data architecture', 'data ethics', 'no-code',
    'low-code', 'zapier', 'integromat', 'microsoft power automate', 'business automation', 'robotic process automation',
    'blue prism', 'uipath', 'automation anywhere', 'aiops', 'itil', 'it service management', 'cloud infrastructure',
    'devsecops', 'site reliability engineer', 'observability', 'prometheus', 'grafana', 'elastic stack', 'log analysis',
    'monitoring', 'alerts', 'slack', 'microsoft teams', 'confluence', 'jira', 'trello', 'asana', 'monday.com',
    'clickup', 'crm systems', 'zoho crm', 'hubspot crm', 'customer experience', 'ux research', 'usability testing',
    'heuristic evaluation', 'persona creation', 'customer journey mapping', 'a/b testing', 'multivariate testing',
    'conversion rate optimization', 'heatmaps', 'usability analysis', 'session recording', 'customer feedback',
    'surveys', 'focus groups', 'market analysis', 'competitive analysis', 'swot analysis', 'business analysis',
    'requirements gathering', 'stakeholder management', 'project planning', 'project scheduling', 'resource allocation',
    'risk mitigation', 'change management', 'stakeholder communication', 'presentation skills', 'microsoft powerpoint',
    'google slides', 'public speaking', 'meeting facilitation', 'team collaboration', 'cross-functional teams',
    'mentoring', 'coaching', 'conflict resolution', 'emotional intelligence', 'time management', 'organizational skills',
    'delegation', 'decision making', 'strategic thinking', 'adaptability', 'creativity', 'innovation', 'problem-solving',
    'critical thinking', 'attention to detail', 'multitasking', 'prioritization', 'stress management', 'workplace diversity',
    'inclusion', 'employee engagement', 'talent acquisition', 'recruiting', 'onboarding', 'performance management',
    'succession planning', 'compensation and benefits', 'employee relations', 'labor law', 'hr policies', 'hr strategy',
    'payroll', 'hr analytics', 'organizational development', 'training and development', 'e-learning', 'learning management systems',
    'hr software', 'workday', 'bamboohr', 'adp', 'zoho people', 'hr compliance', 'hr audits', 'conflict resolution',
    'employee retention', 'cultural awareness', 'diversity and inclusion', 'language skills', 'multilingual',
    'customer support', 'helpdesk', 'technical support', 'client relationship management', 'key account management',
    'sales', 'business development', 'lead generation', 'cold calling', 'client presentations', 'sales forecasting',
    'territory management', 'channel sales', 'partnership management', 'vendor relations', 'contract negotiation',
    'deal closing', 'upselling', 'cross-selling', 'salesforce crm', 'pipelines', 'quotas', 'sales targets', 'prospecting',
    'customer retention', 'market segmentation', 'pricing strategies', 'distribution channels', 'digital transformation',
    'business process improvement', 'lean methodologies', 'six sigma', 'kaizen', 'root cause analysis', 'business process modeling',
    'continuous improvement', 'operations management', 'manufacturing processes', 'quality control', 'quality assurance',
    'supply chain optimization', 'inventory management', 'warehouse management', 'logistics planning', 'transportation management',
    'fleet management', 'export/import', 'global trade', 'customs regulations', 'sustainability', 'green logistics', 'lean manufacturing',
    'iso standards', 'product lifecycle management', 'product innovation', 'design thinking', 'rapid prototyping',
    'hardware design', 'electronics', 'circuit design', 'pcb design', 'embedded systems', 'firmware development', 'internet of things (IoT)',
    'sensor networks', 'signal processing', 'automation systems', 'robotic process automation (RPA)', 'industrial automation',
    'manufacturing execution systems (MES)', 'robotics programming', 'plc programming', 'scada systems', 'machine learning operations (MLOps)',
    'data pipelines', 'data security', 'privacy by design', 'identity management', 'multi-factor authentication', 'zero trust architecture',
    'penetration testing tools', 'vulnerability scanning', 'cyber threat intelligence', 'threat hunting', 'risk mitigation strategies',
    'incident detection', 'security awareness training', 'phishing prevention', 'email security', 'encryption techniques', 'key management',
    'certificate management', 'public key infrastructure (PKI)', 'cloud security', 'virtual private networks (VPN)', 'security operations center (SOC)',
    'security orchestration', 'managed security services', 'network security monitoring', 'intrusion detection', 'malware analysis',
    'advanced persistent threats (APTs)', 'threat modeling', 'business impact analysis', 'disaster recovery planning', 'data loss prevention',
    'email encryption', 'mobile device management', 'endpoint protection', 'secure coding practices', 'application security',
    'database security', 'server hardening', 'patch management', 'network segmentation', 'firewall policies', 'backup strategies',
    'system monitoring', 'log management', 'business continuity planning', 'crisis management', 'supply chain security', 'third-party risk management',
    'cloud infrastructure security', 'container security', 'serverless architecture', 'security compliance frameworks', 'vulnerability management systems',
    'threat assessment', 'risk governance', 'corporate compliance', 'policy development', 'internal audits', 'governance frameworks',
    'data privacy laws', 'data retention policies', 'data breach response', 'data sovereignty', 'cross-border data transfers', 'data protection officers (DPO)',
    'information security management systems (ISMS)', 'cyber risk assessment', 'cyber incident response plans', 'threat intelligence platforms',
    'cybersecurity regulations', 'third-party risk assessments', 'vendor security assessments', 'cybersecurity strategy', 'security risk management',
    'strategic planning', 'financial acumen', 'budget management', 'financial forecasting', 'cost optimization', 'profitability analysis',
    'margin analysis', 'cash flow management', 'capital budgeting', 'investment analysis', 'portfolio management', 'financial statements analysis',
    'financial reporting', 'taxation', 'audit management', 'compliance audits', 'accounting standards', 'GAAP', 'IFRS', 'forensic accounting',
    'internal controls', 'fraud detection', 'financial software', 'quickbooks', 'xero', 'netsuite', 'oracle financials', 'sap finance',
    'tax compliance', 'payroll management', 'investment banking', 'commercial banking', 'private equity', 'venture capital', 'asset management',
    'wealth management', 'financial planning', 'estate planning', 'retirement planning', 'pension funds', 'insurance', 'underwriting', 'claims management',
    'risk management', 'actuarial science', 'quantitative finance', 'algorithmic trading', 'derivatives', 'options trading', 'hedge funds',
    'portfolio diversification', 'fixed income analysis', 'equity research', 'investment risk', 'financial markets', 'economic analysis',
    'macroeconomics', 'microeconomics', 'stock market analysis', 'bond markets', 'commodities trading', 'forex trading', 'financial derivatives',
    'currency hedging', 'financial modeling', 'valuation', 'mergers and acquisitions', 'corporate finance', 'investment strategy', 'credit analysis',
    'credit risk', 'financial advisory', 'tax advisory', 'legal compliance', 'regulatory compliance', 'contract law', 'corporate governance',
    'intellectual property', 'trademark law', 'patent law', 'employment law', 'labor law', 'environmental law', 'antitrust law', 'human rights law',
    'international trade law', 'arbitration', 'litigation', 'dispute resolution', 'contract negotiation', 'public policy', 'policy analysis',
    'legislative affairs', 'government relations', 'lobbying', 'nonprofit management', 'grant writing', 'fundraising', 'corporate social responsibility (CSR)',
    'sustainability reporting', 'social impact', 'impact investing', 'philanthropy', 'social entrepreneurship', 'nonprofit governance', 'board management',
    'program management', 'volunteer management', 'grant management', 'public relations', 'media relations', 'crisis communications', 'reputation management',
    'brand management', 'influencer marketing', 'event planning', 'public speaking', 'media training', 'content strategy', 'content marketing',
    'social media strategy', 'search engine optimization (SEO)', 'search engine marketing (SEM)', 'digital advertising', 'paid search advertising',
    'display advertising', 'affiliate marketing', 'influencer partnerships', 'brand partnerships', 'content partnerships', 'email automation',
    'marketing automation', 'lead generation', 'sales funnel optimization', 'customer acquisition', 'customer retention strategies', 'growth hacking',
    'business-to-business (B2B) marketing', 'business-to-consumer (B2C) marketing', 'content management systems (CMS)', 'wordpress', 'drupal',
    'joomla', 'magento', 'shopify', 'e-commerce platforms', 'online marketplaces', 'user experience (UX)', 'user interface (UI)', 'web development',
    'web design', 'mobile app development', 'mobile app design', 'ios development', 'android development', 'cross-platform app development',
    'react native', 'flutter', 'xamarin', 'app store optimization (ASO)', 'mobile analytics', 'mobile marketing', 'push notifications',
    'app monetization', 'mobile payments', 'blockchain technology', 'cryptocurrency', 'bitcoin', 'ethereum', 'smart contracts', 'distributed ledger technology',
    'fintech', 'decentralized finance (DeFi)', 'regtech', 'insurtech', 'digital wallets', 'mobile banking', 'robo-advisors', 'peer-to-peer lending',
    'online payments', 'payment gateways', 'e-commerce payments', 'point-of-sale systems', 'contactless payments', 'digital currency exchanges',
    'cryptocurrency wallets', 'blockchain development', 'cryptographic algorithms', 'distributed systems', 'hyperledger', 'smart contract development',
    'blockchain governance', 'tokenomics', 'initial coin offerings (ICOs)', 'security token offerings (STOs)', 'stablecoins', 'digital identity management',
    'decentralized applications (dApps)', 'decentralized autonomous organizations (DAOs)', 'blockchain scalability', 'blockchain interoperability',
    'quantum computing', 'artificial intelligence', 'machine learning', 'deep learning', 'neural networks', 'reinforcement learning', 'supervised learning',
    'unsupervised learning', 'natural language processing', 'computer vision', 'generative adversarial networks (GANs)', 'convolutional neural networks (CNNs)',
    'recurrent neural networks (RNNs)', 'long short-term memory (LSTM)', 'attention mechanisms', 'transformer models', 'deep reinforcement learning',
    'autoencoders', 'self-supervised learning', 'few-shot learning', 'meta-learning', 'multi-agent systems', 'swarm intelligence', 'genetic algorithms',
    'fuzzy logic', 'evolutionary algorithms', 'game theory', 'knowledge representation', 'symbolic reasoning', 'machine reasoning', 'probabilistic graphical models',
    'bayesian networks', 'decision trees', 'random forests', 'support vector machines', 'gradient boosting', 'xgboost', 'lightgbm', 'catboost',
    'ensemble learning', 'hyperparameter tuning', 'model evaluation', 'cross-validation', 'feature engineering', 'engineer', 'dimensionality reduction',
    'principal component analysis (PCA)', 'singular value decomposition (SVD)', 't-SNE', 'umap', 'latent dirichlet allocation (LDA)', 'clustering algorithms',
    'k-means clustering', 'hierarchical clustering', 'dbscan', 'agglomerative clustering', 'fuzzy c-means', 'outlier detection', 'anomaly detection',
    'time series analysis', 'seasonal decomposition', 'exponential smoothing', 'autoregressive integrated moving average (ARIMA)', 'holt-winters',
    'prophet', 'facebook prophet', 'state-space models', 'kalman filter', 'particle filter', 'hidden markov models', 'bayesian inference',
    'monte carlo simulation', 'markov chain monte carlo (MCMC)', 'importance sampling', 'rejection sampling', 'sequential monte carlo', 'variational inference',
    'generative models', 'bayesian optimization', 'reinforcement learning algorithms', 'q-learning', 'deep q-networks (DQN)', 'policy gradient methods',
    'actor-critic methods', 'proximal policy optimization (PPO)', 'trust region policy optimization (TRPO)', 'a3c', 'soft actor-critic (SAC)',
    'continuous action spaces', 'multi-agent reinforcement learning', 'markov decision processes', 'partially observable markov decision processes',
    'stochastic processes', 'dynamic programming', 'backpropagation through time', 'vanishing gradient problem', 'exploding gradient problem',
    'transfer learning', 'domain adaptation', 'zero-shot learning', 'self-attention', 'transformer models', 'pre-trained models', 'fine-tuning',
    'adversarial machine learning', 'robust machine learning', 'explainable artificial intelligence (XAI)', 'fairness in AI', 'ethics in AI',
    'responsible AI', 'artificial general intelligence (AGI)', 'artificial superintelligence (ASI)', 'human-computer interaction', 'brain-computer interfaces',
    'neurotechnology', 'biometric authentication', 'gesture recognition', 'voice recognition', 'speech synthesis', 'text-to-speech', 'speech-to-text',
    'language modeling', 'machine translation', 'sequence-to-sequence models', 'attention mechanisms', 'transformer models', 'word embeddings',
    'contextual word embeddings', 'sentence embeddings', 'document embeddings', 'topic modeling', 'text classification', 'named entity recognition (NER)',
    'part-of-speech tagging', 'dependency parsing', 'syntactic parsing', 'semantic role labeling', 'coreference resolution', 'question answering',
    'machine reading comprehension', 'text summarization', 'extractive summarization', 'abstractive summarization', 'machine translation', 'word embeddings',
    'sentence embeddings', 'contextual embeddings', 'transformer models', 'pretrained language models', 'gpt',
    'electra', 'longformer', 'bart', 'pegasus', 'xlm', 'xlm-roberta', 'text-to-image models', 'dall-e', 'image generation', 'stable diffusion',
    'text-to-speech', 'waveglow', 'wavenet', 'vq-vae', 'neural vocoder', 'voice conversion', 'singing synthesis', 'visual question answering (VQA)',
    'image captioning', 'video understanding', 'image segmentation', 'object detection', 'instance segmentation', 'semantic segmentation',
    'panoptic segmentation', 'bounding box regression', 'anchor-based models', 'anchor-free models', 'spatial transformers', 'point cloud processing',
    '3d reconstruction', 'mesh generation', 'point cloud classification', 'volumetric segmentation', 'physics-based rendering', 'ray tracing',
    'global illumination', 'path tracing', 'light field rendering', 'voxel-based rendering', 'real-time ray tracing', 'photon mapping', 'neural rendering',
    'deep learning-based rendering', 'adversarial rendering', 'differentiable rendering', 'self-supervised learning', 'contrastive learning',
    'representation learning', 'feature disentanglement', 'style transfer', 'generative models', 'vae', 'variational autoencoders', 'gan',
    'generative adversarial networks', 'conditional gans', 'cyclegan', 'biggan', 'stylegan', 'image-to-image translation', 'video-to-video translation',
    'super-resolution', 'image denoising', 'image inpainting', 'image-to-text models', 'text-to-image models', '3d generation', 'mesh generation',
    'surface reconstruction', 'texture generation', 'neural texture generation', 'self-attention', 'multi-head attention', 'transformers',
    'pre-trained models', 'transfer learning', 'few-shot learning', 'meta-learning', 'online learning', 'contrastive learning', 'self-supervised learning',
    'representation learning', 'multi-modal learning', 'cross-modal learning', 'zero-shot learning', 'unsupervised learning', 'semi-supervised learning',
    'domain adaptation', 'generalization in ai', 'robustness in ai', 'safety in ai', 'ethics in ai', 'fairness in ai', 'responsible ai', 'accountability in ai',
    'ai governance', 'regulation in ai', 'law and ai', 'policy for ai', 'ai and human rights', 'social implications of ai', 'economic impacts of ai',
    'ai and automation', 'ai and jobs', 'ai and the future of work', 'human-centered ai', 'user experience (ux) for ai', 'human-computer interaction (hci)',
    'neuro-symbolic ai', 'causal inference', 'causal discovery', 'reinforcement learning', 'multi-agent reinforcement learning', 'inverse reinforcement learning',
    'safe reinforcement learning', 'hierarchical reinforcement learning', 'meta-reinforcement learning', 'model-based reinforcement learning',
    'policy gradient methods', 'trust region policy optimization (trpo)', 'proximal policy optimization (ppo)', 'actor-critic methods', 'asynchronous actor-critic methods (a3c)',
    'continuous action spaces', 'multi-agent systems', 'swarm intelligence', 'genetic algorithms', 'evolutionary algorithms', 'genetic programming',
    'swarm intelligence', 'ant colony optimization', 'particle swarm optimization', 'simulated annealing', 'tabu search', 'gradient-based optimization',
    'convex optimization', 'non-convex optimization', 'stochastic gradient descent', 'adam optimizer', 'gradient clipping', 'gradient penalty',
    'learning rate scheduling', 'hyperparameter optimization', 'model selection', 'cross-validation', 'grid search', 'random search',
    'bayesian optimization', 'neural architecture search', 'automl', 'meta-learning', 'few-shot learning', 'zero-shot learning', 'domain adaptation',
    'transfer learning', 'fine-tuning', 'multi-task learning', 'multi-modal learning', 'cross-modal learning', 'multi-agent learning', 'federated learning',
    'distributed learning', 'on-device learning', 'privacy-preserving machine learning', 'differential privacy', 'homomorphic encryption',
    'secure multi-party computation', 'blockchain technology', 'decentralized ai', 'federated learning', 'data privacy', 'data security',
    'encryption algorithms', 'hashing algorithms', 'elliptic curve cryptography', 'rsa', 'digital signatures', 'public key infrastructure (pki)',
    'blockchain technology', 'smart contracts', 'distributed ledger technology (dlt)', 'consensus mechanisms', 'proof of work (pow)', 'proof of stake (pos)',
    'delegated proof of stake (dpos)', 'byzantine fault tolerance (bft)', 'proof of authority (poa)', 'proof of elapsed time (poet)', 'cryptocurrency',
    'blockchain applications', 'tokenomics', 'initial coin offerings (icos)', 'security token offerings (stos)', 'stablecoins', 'decentralized finance (defi)',
    'governance tokens', 'staking', 'yield farming', 'liquidity mining', 'decentralized exchanges (dex)', 'centralized exchanges (cex)', 'crypto wallets',
    'cold wallets', 'hot wallets', 'multi-signature wallets', 'crypto custody', 'blockchain interoperability', 'sidechains', 'layer 2 scaling solutions',
    'rollups', 'zk-rollups', 'optimistic rollups', 'layer 1 protocols', 'solana', 'ethereum', 'bitcoin', 'polkadot', 'cosmos', 'avalanche',
    'blockchain development', 'blockchain governance', 'dao', 'decentralized autonomous organizations', 'defi', 'yield farming', 'staking', 'liquidity'
]