COURSES = {
    'Bachelor of Science in Computer Engineering': {'BS Computer Engineering', 'B.S. CEng', 'Computer Engineering'},
    'Bachelor of Science in Information Technology': {'BS Information Technology', 'B.S. IT', 'Information Technology', 'Bachelor of Science in Information Technology'},  # Updated entry
    'Bachelor of Science in Nursing': {'BS Nursing', 'B.S. Nursing'},
    'Bachelor of Arts in Psychology': {'BA Psychology', 'B.A. Psychology'},
    'Associate in Computer Science': {'Associate in Computer Science', 'A.S. Computer Science'},
    'Diploma in Business Administration': {'Diploma in Business Administration', 'Business Administration'},
    'Bachelor of Science in Accountancy': {'BS Accountancy', 'B.S. Accountancy'},
    'Bachelor of Science in Education': {'BS Education', 'B.S. Ed'},
    'Bachelor of Arts in English Language': {'BA English', 'B.A. English Language'},
    'Bachelor of Science in Civil Engineering': {'BS Civil Engineering', 'B.S. CEng'},
    'Bachelor of Science in Mechanical Engineering': {'BS Mechanical Engineering', 'B.S. MEng'},
    'Bachelor of Laws': {'LLB', 'Bachelor of Laws'},
    'Bachelor of Science in Marine Biology': {'BS Marine Biology', 'B.S. MarBio'},
    'Bachelor of Arts in Hospitality Management': {'BA Hospitality Management', 'B.A. HM'},
    'Associate in Hotel and Restaurant Management': {'Associate in HRM', 'A.S. HRM'},
    'Diploma in Tourism': {'Diploma in Tourism', 'Tourism'},
    'Bachelor of Science in Business Administration': {'BS Business Administration', 'B.A. Business Administration'}, 
    'Bachelor of Science in Marketing': {'BS Marketing', 'B.S. Mktg'},
    'Bachelor of Science in Entrepreneurship': {'BS Entrepreneurship', 'B.S. Entrep'},
    'Bachelor of Science in Accountancy Technology': {'BS Accountancy Technology', 'BS AcTech'},
    'Bachelor of Arts in Communication Arts': {'BA Communication Arts', 'B.A. Comm Arts'},
    'Bachelor of Science in Criminology': {'BS Criminology', 'B.S. Crim'},
    'Bachelor of Science in Agriculture': {'BS Agriculture', 'B.S. Agric'},
    'Bachelor of Science in Biology': {'BS Biology', 'B.S. Bio'},
    'Bachelor of Science in Pharmacy': {'BS Pharmacy', 'B.S. Pharm'},
    'Bachelor of Science in Data Science': {'BS Data Science', 'Data Science'},  
    'Bachelor of Science in Information Systems': {'BS Information Systems', 'Information Systems'},
    'Bachelor of Science in Electronics Engineering': {'BS Electronics Engineering', 'B.S. EEE'},
    'Associate in Multimedia Arts and Animation': {'Associate in Multimedia Arts', 'A.S. Multimedia Arts'},  
    'Diploma in Web Development': {'Diploma in Web Development', 'Web Development'},
    'Bachelor of Science in Cybersecurity': {'BS Cybersecurity', 'Cybersecurity'},  
    'Bachelor of Engineering in Computer Engineering': {'B.E. IN COMPUTER', 'B.E', 'Engineering'},  
    'Bachelor of Technology in Computer Science': {'B.Tech', 'B.Sc', 'Engineering', 'Computer Science'},  
    'Diploma in Engineering': {'Diploma in Engineering', 'Engineering'},  
    'Bachelor of Science in Technology': {'BS Technology', 'B.S. Tech', 'Technology'},
}