SKILLS_DB = [
    'machine learning',
    'data science',
    'python',
    'word',
    'excel',
    'english',
    'java',
    'javascript',
    'sql',  
    'r',
    'tableau',
    'project management',
    'leadership',
    'communication skills',
    'problem-solving',
    'html',
    'css',
    'git',
    'agile methodologies',
    'customer service',
    'mysql',
    'postgresql',
    'oracle',
    'db2',  
    'sql server',  
    'mongodb',
    'cassandra', 
    'couchbase',  
    'application programming',
    'system administration',
]