export const skillWeights = {
  'javascript': 2,
  'react': 1.5,
  'node.js': 1.8,
  'html': 1.2,
  'css': 1.1,
  'sql': 1.7,
  'python': 2.2,
  'java': 1.9,
  'c++': 1.6,
  'php': 1.4,
  'typescript': 1.8,
  'docker': 2.0,
  'kubernetes': 2.3,
  'aws': 2.5,
  'azure': 2.1,
  'git': 1.3,
  'linux': 1.7,
  'bash': 1.4,
  'graphql': 1.9,
  'mongodb': 1.5,
  'firebase': 1.8,
  'flutter': 2.1,
  'android': 1.6,
  'ios': 1.7,
  'angular': 1.9,
  'vue.js': 1.6,
  'swift': 2.0,
  'go': 2.2,
  'rust': 2.4,
  'ruby': 1.5,
  'perl': 1.4,
  'django': 2.1,
  'flask': 1.8,
  'spring': 1.9,
  'hibernate': 1.7,
  'postgresql': 2.0,
  'mysql': 1.6,
  'redis': 1.7,
  'elasticsearch': 2.3,
  'graphql': 1.8,
  'websockets': 1.5,
  'tensorflow': 2.4,
  'pytorch': 2.5,
  'machine learning': 2.7,
  'deep learning': 2.8,
  'nlp': 2.3,
  'opencv': 2.0,
  'pandas': 2.1,
  'numpy': 1.9,
  'scikit-learn': 2.4,
  'keras': 2.2,
  'big data': 2.6,
  'hadoop': 2.5,
  'spark': 2.6,
  'data science': 2.7,
  'data analysis': 2.1,
  'cloud computing': 2.5,
  'blockchain': 2.4,
  'cybersecurity': 2.7,
  'ethical hacking': 2.6,
  'penetration testing': 2.5,
  'docker-compose': 1.7,
  'terraform': 2.3,
  'ansible': 1.8,
  'puppet': 1.7,
  'saltstack': 1.6,
  'jenkins': 1.9,
  'circleci': 1.8,
  'travisci': 1.7,
  'ci/cd': 2.2,
  'devops': 2.4,
  'agile': 1.7,
  'scrum': 1.6,
  'kanban': 1.5,
  'jira': 1.3,
  'confluence': 1.2,
  'microsoft azure': 2.2,
  'gcp': 2.4,
  'cloudformation': 2.1,
  'azure pipelines': 2.0,
  'microservices': 2.5,
  'event-driven architecture': 2.4,
  'serverless': 2.3,
  'graphql api': 1.9,
  'rest api': 1.8,
  'oauth': 1.7,
  'json web tokens': 1.6,
  'sso': 1.5,
  'saml': 1.6,
  'ldap': 1.4,
  'vpn': 1.5,
  'wireguard': 1.6,
  'openvpn': 1.7,
  'prometheus': 2.0,
  'grafana': 2.1,
  'zabbix': 1.9,
  'splunk': 2.2,
  'datadog': 2.3,
  'new relic': 2.0,
  'aws lambda': 2.5
};
